"""
AI DECLARATION: THIS FILE WAS GENERATED BY AI (Claude Sonnet 4.6).
It is only used for quick validation.

Smoke test — environment mechanics for Experiment 3 (BASt) and Experiment 4 (NOEVs).

Part 1 (this file): exercises everything EXCEPT the neural network:
  - BASt scenario: random 2022 date, departure-time distribution, 24h truncation
  - Cross-N: vehicles_to_spawn < max_vehicles, variable spawn counts across episodes
  - Observation shapes, padding, vehicle_mask consistency, value ranges
  - NOEV injection via Random_Data_Provider (Exp 4 plumbing)

Run:  python smoke_test_env.py
Requires SUMO (SUMO_HOME set or eclipse-sumo pip package), no torch needed.
"""
import os, sys, traceback
import numpy as np

PASS, FAIL = "  [PASS]", "  [FAIL]"
failures = []

def check(name, cond, detail=""):
    print((PASS if cond else FAIL), name, ("- " + str(detail) if detail and not cond else ""))
    if not cond:
        failures.append((name, detail))

def run_episode(env, policy="random", max_steps=20000, rng=None):
    """Roll one episode with a trivial policy; return per-step stats."""
    rng = rng or np.random.default_rng(0)
    obs, info = env.reset()
    n_steps, terminated, truncated = 0, False, False
    mask_counts, sim_times = [], []
    while not (terminated or truncated) and n_steps < max_steps:
        action = 0 if policy == "noop" else int(rng.integers(0, env.action_space.n))
        obs, reward, terminated, truncated, info = env.step(action)
        # --- shape & range checks on every step (cheap) ---
        assert obs["active_vehicle"].shape == (12,), obs["active_vehicle"].shape
        assert obs["other_vehicles"].shape == (env.max_vehicles, 12)
        assert obs["vehicle_mask"].shape == (env.max_vehicles,)
        assert set(np.unique(obs["vehicle_mask"])).issubset({0.0, 1.0})
        finite = obs["other_vehicles"][obs["vehicle_mask"] == 1.0]
        if finite.size:
            assert finite.min() >= -1.0 - 1e-6 and finite.max() <= 1.0 + 1e-6, \
                f"obs out of [-1,1]: min={finite.min()}, max={finite.max()}"
        if "simulation_time" in obs:
            sim_times.append(float(obs["simulation_time"][0]))
        mask_counts.append(int(obs["vehicle_mask"].sum()))
        n_steps += 1
    return dict(steps=n_steps, terminated=terminated, truncated=truncated,
                max_active=max(mask_counts) if mask_counts else 0,
                sim_time_final=sim_times[-1] if sim_times else None)

def main():
    from environment import CustomEnv

    # ----------------------------------------------------------------------
    print("\n=== Test 1: BASt scenario, cross-N (Experiment 3 core path) ===")
    env = None
    try:
        env = CustomEnv(
            scenario_generator="bast",
            vehicles_to_spawn=8,        # daily maximum in BASt mode
            max_vehicles=15,            # cross-N: obs padded beyond spawn count
            obs_features={"simulation_time"},
            street_network="straight_100km",
            random_seed=42,
        )
        check("env constructed (scenario='bast')", True)
        check("24h truncation set", env.truncate_after_n_simulation_steps == 24 * 3600,
              env.truncate_after_n_simulation_steps)
        check("obs space padded to max_vehicles=15",
              env.observation_space["other_vehicles"].shape == (15, 12))

        spawn_counts = []
        for ep in range(2):
            stats = run_episode(env, policy="random")
            spawn_counts.append(stats["max_active"])
            print(f"  episode {ep}: steps={stats['steps']} "
                  f"max_active_vehicles={stats['max_active']} "
                  f"terminated={stats['terminated']} truncated={stats['truncated']} "
                  f"final_sim_time(norm)={stats['sim_time_final']}")
            check(f"ep{ep} ended properly", stats["terminated"] or stats["truncated"])
            check(f"ep{ep} active vehicles <= max_vehicles", stats["max_active"] <= 15)
        check("BASt produces vehicles", max(spawn_counts) > 0, spawn_counts)
        print(f"  spawn counts across episodes: {spawn_counts} "
              "(variation across episodes/dates is expected)")
    except Exception as e:
        traceback.print_exc()
        check("Test 1 ran without exception", False, e)
    finally:
        if env is not None:
            try: env.close()
            except Exception: pass

    # ----------------------------------------------------------------------
    print("\n=== Test 2: NOEV plumbing via Random_Data_Provider (Experiment 4 path) ===")
    env = None
    try:
        env = CustomEnv(
            scenario_generator="all_random",
            vehicles_to_spawn=3,
            non_observable_vehicles=5,
            obs_features={"simulation_time"},
            street_network="straight_100km",
            random_seed=7,
        )
        stats = run_episode(env, policy="random")
        check("NOEV episode completed", stats["terminated"] or stats["truncated"], stats)
        print(f"  steps={stats['steps']} max_active(OEVs only)={stats['max_active']}")
        check("NOEVs not visible in observation mask", stats["max_active"] <= 3,
              "mask should count OEVs only")
    except Exception as e:
        traceback.print_exc()
        check("Test 2 ran without exception", False, e)
    finally:
        if env is not None:
            try: env.close()
            except Exception: pass

    # ----------------------------------------------------------------------
    print("\n=== Summary ===")
    if failures:
        print(f"{len(failures)} FAILURE(S):")
        for name, detail in failures:
            print("  -", name, "|", detail)
        sys.exit(1)
    print("All environment-level checks passed.")

if __name__ == "__main__":
    main()
