"""
AI DECLARATION: THIS FILE WAS GENERATED BY AI (Claude Sonnet 4.6).
It is only used for quick validation.

Validate that libsumo and TraCI produce identical results on the same seed.

Run TWICE — once per backend — in two separate terminal sessions:

    USE_LIBSUMO=1 python validate_libsumo.py   # or just: python validate_libsumo.py
    USE_LIBSUMO=0 python validate_libsumo.py

Each run writes a JSON results file. The script then compares them and
reports any differences. If a second results file already exists when
you run it, comparison happens automatically.

Usage after implementing the libsumo/traci _select_backend() switch.
Until then the USE_LIBSUMO env var won't exist in your code yet, so run
this script as a plain timing + sanity check first:
    python validate_libsumo.py
"""

import json, os, sys, time
import numpy as np

SEED        = 42
N_EPISODES  = 3
N_VEHICLES  = 20
SCENARIO    = "bast"
NETWORK     = "straight_100km"
OUTPUT_DIR  = "."

RESULTS_LIBSUMO = os.path.join(OUTPUT_DIR, "validate_results_libsumo.json")
RESULTS_TRACI   = os.path.join(OUTPUT_DIR, "validate_results_traci.json")

# ── backend detection ────────────────────────────────────────────────────────
# Once you've implemented _select_backend() in simulation.py, this block does
# nothing — your code picks the backend automatically via USE_LIBSUMO.
# Until then it redirects the import so you can still time both paths.
use_libsumo = os.environ.get("USE_LIBSUMO", "1") == "1"
if use_libsumo:
    try:
        import libsumo
        sys.modules.setdefault("traci", libsumo)   # redirect before simulation.py loads
        backend_name = "libsumo"
    except ImportError:
        print("libsumo not installed — pip install libsumo==1.26.0")
        sys.exit(1)
else:
    backend_name = "traci"

from environment import CustomEnv   # imports simulation.py which imports traci/libsumo

# ── run episodes ─────────────────────────────────────────────────────────────
def run(n_episodes, seed, n_vehicles, scenario, network):
    results = []
    rng = np.random.default_rng(seed)

    env = CustomEnv(
        scenario_generator=scenario,
        vehicles_to_spawn=n_vehicles,
        max_vehicles=n_vehicles,
        obs_features={"simulation_time"},
        street_network=network,
        random_seed=seed,
    )

    for ep in range(n_episodes):
        ep_seed = seed + ep
        obs, info = env.reset(seed=ep_seed)
        terminated = truncated = False
        ep_reward = 0.0
        ep_steps  = 0

        while not (terminated or truncated):
            action = int(rng.integers(0, env.action_space.n))
            obs, reward, terminated, truncated, info = env.step(action)
            ep_reward += reward
            ep_steps  += 1

        metrics = info.get("_episode_metrics", {})
        results.append({
            "episode":      ep,
            "seed":         ep_seed,
            "steps":        ep_steps,
            "reward":       round(ep_reward, 6),
            "terminated":   terminated,
            "truncated":    truncated,
            **{k: round(v, 6) if isinstance(v, float) else v
               for k, v in metrics.items()},
        })
        print(f"  ep{ep}: steps={ep_steps} reward={ep_reward:.2f} "
              f"ttt={metrics.get('global_ttt','?')} "
              f"empty={metrics.get('empty_vehicles_per_episode','?')} "
              f"cwt={metrics.get('cumulated_waiting_time','?'):.1f}"
              if isinstance(metrics.get('cumulated_waiting_time'), float)
              else f"  ep{ep}: steps={ep_steps} reward={ep_reward:.2f} metrics={metrics}")

    env.close()
    return results

# ── compare two result files ──────────────────────────────────────────────────
TOLERANCE = 1e-3   # allow tiny float rounding differences between backends

def compare(path_a, path_b):
    a = json.load(open(path_a))
    b = json.load(open(path_b))

    keys_to_check = [
        "steps", "reward", "terminated", "truncated",
        "global_ttt", "cumulated_waiting_time",
        "empty_vehicles_per_episode", "arrival_soc_wh_mean",
        "charging_stops_per_episode_mean",
    ]

    diffs = []
    for i, (ra, rb) in enumerate(zip(a, b)):
        for k in keys_to_check:
            va, vb = ra.get(k), rb.get(k)
            if va is None or vb is None:
                continue
            if isinstance(va, float) or isinstance(vb, float):
                if abs(float(va) - float(vb)) > TOLERANCE:
                    diffs.append(f"  ep{i} {k}: libsumo={va} traci={vb} Δ={abs(va-vb):.6f}")
            elif va != vb:
                diffs.append(f"  ep{i} {k}: libsumo={va} traci={vb}")

    if diffs:
        print(f"\n{'='*60}")
        print(f"DIFFERENCES FOUND ({len(diffs)}):")
        for d in diffs:
            print(d)
        print(f"{'='*60}")
        print("\nIf differences are in metrics only (not steps/reward/terminated),")
        print("check VAR_WAITING_TIME sampling — libsumo and TraCI may tick")
        print("vehicle timers slightly differently. Steps and reward MUST match.")
    else:
        print(f"\n{'='*60}")
        print("ALL CHECKS PASSED — libsumo and TraCI results are identical.")
        print(f"{'='*60}")

# ── main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    out_path = RESULTS_LIBSUMO if use_libsumo else RESULTS_TRACI
    other_path = RESULTS_TRACI if use_libsumo else RESULTS_LIBSUMO

    print(f"Backend : {backend_name}")
    print(f"Scenario: {SCENARIO}, network={NETWORK}, "
          f"vehicles={N_VEHICLES}, seed={SEED}, episodes={N_EPISODES}\n")

    t0 = time.perf_counter()
    results = run(N_EPISODES, SEED, N_VEHICLES, SCENARIO, NETWORK)
    elapsed = time.perf_counter() - t0

    json.dump(results, open(out_path, "w"), indent=2)
    print(f"\nWall time : {elapsed:.1f}s total, {elapsed/N_EPISODES:.1f}s per episode")
    print(f"Results   : {out_path}")

    if os.path.exists(other_path):
        print(f"\nFound {other_path} — comparing now...")
        compare(RESULTS_LIBSUMO, RESULTS_TRACI)
    else:
        other_backend = "TraCI" if use_libsumo else "libsumo"
        print(f"\nNow run with the other backend to compare:")
        print(f"  USE_LIBSUMO={'0' if use_libsumo else '1'} python validate_libsumo.py")
